#!/usr/bin/env bash
# ============================================================================
#  40-apply-services.sh — declare-and-converge application runtime.
#  Services come from manifest/services.json (code lives in this repo, data and
#  config are restored from the memory repository by 20-restore.sh).
#  systemd units when available, supervised background process otherwise.
# ============================================================================
export LOG_TAG=services
. "$(dirname "$0")/lib/common.sh"
. "$SCRIPT_DIR/lib/memrepo.sh"
load_config

START="$(now)"
NODE_STATE_DIR="$INSTALL_ROOT/state"
SVC_FILE="$REPO_DIR/manifest/services.json"
[ -s "$SVC_FILE" ] || die "missing manifest/services.json"
mkdir -p "$NODE_STATE_DIR"
RESULT="$NODE_STATE_DIR/services.json"; echo '[]' >"$RESULT"

HAVE_SYSTEMD=0
systemctl is-system-running >/dev/null 2>&1 && HAVE_SYSTEMD=1
[ "$HAVE_SYSTEMD" = 1 ] || warn "systemd not usable — using supervised background processes"

_start_service() { # name unit_cmd
  local name="$1" execline="$2"
  if [ "$HAVE_SYSTEMD" = 1 ]; then
    sudo systemctl daemon-reload >/dev/null 2>&1 || true
    sudo systemctl restart "mrphon3shop-${name}.service" >/dev/null 2>&1 && return 0
    sudo systemctl start "mrphon3shop-${name}.service" >/dev/null 2>&1 && return 0
    return 1
  fi
  sudo pkill -f "mrphon3shop/${name}/runner.sh" >/dev/null 2>&1 || true
  printf '%s\n' "#!/usr/bin/env bash" "exec $execline" >"/opt/mrphon3shop/apps/${name}/runner.sh"
  sudo chmod +x "/opt/mrphon3shop/apps/${name}/runner.sh"
  ( cd "$(jq -r --arg n "$name" '.services[]|select(.name==$n)|.workdir // "/"' "$SVC_FILE")" && \
    sudo nohup setsid "/opt/mrphon3shop/apps/${name}/runner.sh" >>"$LOG_ROOT/${name}.log" 2>&1 & )
  return 0
}

_stop_service() { # name
  local name="$1"
  if [ "$HAVE_SYSTEMD" = 1 ]; then
    sudo systemctl disable --now "mrphon3shop-${name}.service" >/dev/null 2>&1 || true
  else
    sudo pkill -f "mrphon3shop/${name}/runner.sh" >/dev/null 2>&1 || true
  fi
}

# routes published by an earlier boot may point at ports we no longer use; the
# serve/funnel config for the app ports is rebuilt below (and again in
# 50-tailscale-funnel.sh for the ssh doors)
sudo tailscale serve reset >/dev/null 2>&1 || true

mapfile -t NAMES < <(jq -r '.services[]?.name' "$SVC_FILE")
for name in "${NAMES[@]}"; do
  [ -z "$name" ] && continue
  svc="$(jq -c --arg n "$name" '.services[]|select(.name==$n)' "$SVC_FILE")"
  step "service: $name"
  enabled="$(jq -r '.enabled // true' <<<"$svc")"
  if [ "$enabled" != "true" ]; then
    log "disabled in manifest — stopping if running"
    _stop_service "$name"
    jq --arg n "$name" '. + [{name:$n, state:"disabled"}]' "$RESULT" >"$RESULT.t" && mv "$RESULT.t" "$RESULT"
    continue
  fi

  # non-apt program this service needs (installed by scripts/35-programs.sh)
  prog="$(jq -r '.program // empty' <<<"$svc")"
  if [ -n "$prog" ] && [ "${SKIP_PROGRAMS:-0}" != "1" ]; then
    bash "$SCRIPT_DIR/35-programs.sh" "$prog" || warn "program $prog failed to install"
  fi

  # per-service first-boot configuration (credentials, TLS material, …)
  setup="$(jq -r '.setup // empty' <<<"$svc")"
  if [ -n "$setup" ] && [ -f "$REPO_DIR/$setup" ]; then
    if ! sudo -E bash "$REPO_DIR/$setup"; then
      warn "$name: setup hook failed — skipping the service"
      jq --arg n "$name" '. + [{name:$n, state:"setup-failed", port:0, data_paths:[], config_paths:[]}]' \
         "$RESULT" >"$RESULT.t" && mv "$RESULT.t" "$RESULT"
      continue
    fi
  fi

  port="$(jq -r '.port // 0' <<<"$svc")"
  workdir="$(jq -r '.workdir // "/"' <<<"$svc")"
  command="$(jq -r '.command' <<<"$svc")"
  cwd="$(jq -r '.configdir // empty' <<<"$svc")"
  edir="$(jq -r '.envdir // empty' <<<"$svc")"

  # data + config directories (these exact paths are what the memory repo stores)
  mapfile -t dpaths < <(jq -r '.data_paths[]?' <<<"$svc")
  mapfile -t cpaths < <(jq -r '.config_paths[]?' <<<"$svc")
  for p in "${dpaths[@]}" "${cpaths[@]}"; do mkdir -p "$p"; done
  [ -n "$cwd" ] && mkdir -p "$cwd"
  [ -n "$edir" ] && mkdir -p "$edir"

  # environment file (config -> persisted)
  if [ -n "$edir" ]; then
    envfile="$edir/env"
    { echo "# generated by 40-apply-services.sh — non-secret runtime env"
      echo "NODE_HOSTNAME=$NODE_HOSTNAME"
      echo "NODE_RUN_ID=${GITHUB_RUN_ID:-local}"
      echo "NODE_DATA_DIR=${dpaths[0]:-/opt/mrphon3shop/data/$name}"
      jq -r '.env // {} | to_entries[] | "\(.key)=\(.value)"' <<<"$svc"
    } >"$envfile"
  fi

  if [ "$HAVE_SYSTEMD" = 1 ]; then
    unit=/etc/systemd/system/mrphon3shop-${name}.service
    sudo tee "$unit" >/dev/null <<EOF
[Unit]
Description=mrphon3shop app: ${name}
After=network-online.target

[Service]
Type=simple
WorkingDirectory=${workdir}
$( [ -n "$edir" ] && echo "EnvironmentFile=-${edir}/env" )
Environment=NODE_HOSTNAME=${NODE_HOSTNAME}
ExecStart=${command}
Restart=$(jq -r '.restart // "always"' <<<"$svc")
RestartSec=2
StartLimitIntervalSec=0
StandardOutput=append:${LOG_ROOT}/${name}.log
StandardError=append:${LOG_ROOT}/${name}.log
KillMode=mixed
TimeoutStopSec=10

[Install]
WantedBy=multi-user.target
EOF
    sudo chmod 644 "$unit"
  fi

  state="starting"
  if ! _start_service "$name" "$command"; then state="failed"; fi

  # health check (bounded, no long sleeps)
  health_type="$(jq -r '.health.type // "tcp"' <<<"$svc")"
  if [ "$state" != failed ]; then
    if [ "$health_type" = http ]; then
      hp="$(jq -r '.health.path // "/"' <<<"$svc")"; want="$(jq -r '.health.expect // 200' <<<"$svc")"
      if wait_http "http://127.0.0.1:${port}${hp}" 20 "$want"; then state=healthy; else state=unhealthy; fi
    else
      if wait_port 127.0.0.1 "$port" 20; then state=healthy; else state=unhealthy; fi
    fi
  fi
  log "service $name -> $state (port $port)"

  # tailnet-only exposure (never public unless the manifest says so)
  if jq -e '.tailnet_serve' <<<"$svc" >/dev/null 2>&1; then
    spath="$(jq -r '.tailnet_serve.path // ("/"+$n)' --arg n "$name" <<<"$svc")"
    sport="$(jq -r '.tailnet_serve.port // 443' <<<"$svc")"
    sudo tailscale serve --bg "--https=${sport}" "--set-path=${spath}" "http://127.0.0.1:${port}" >/dev/null 2>&1 \
      || sudo tailscale serve --bg "--https=${sport}" "http://127.0.0.1:${port}" >/dev/null 2>&1 \
      || warn "tailscale serve for $name failed"
  fi
  if [ "$(jq -r '.public // false' <<<"$svc")" = "true" ]; then
    # Public HTTPS through Funnel (the relay terminates TLS). Some backends speak
    # TLS themselves (Apache) — those use the https+insecure scheme.
    scheme="$(jq -r '.backend_scheme // "http"' <<<"$svc")"
    warn "service $name is marked public — exposing through Funnel on 443"
    if sudo tailscale funnel --bg --yes --https=443 "${scheme}://127.0.0.1:${port}" >/dev/null 2>&1; then
      log "public HTTPS door published for $name"
    else
      warn "public expose failed for $name"
    fi
  fi

  jq --arg n "$name" --arg s "$state" --argjson p "${port:-0}" \
     --arg data "$(jq -c '.data_paths // []' <<<"$svc")" --arg cfg "$(jq -c '.config_paths // []' <<<"$svc")" \
     '. + [{name:$n, state:$s, port:$p, data_paths:($data|fromjson), config_paths:($cfg|fromjson)}]' \
     "$RESULT" >"$RESULT.t" && mv "$RESULT.t" "$RESULT"
done

jq --argjson secs "$(( $(now) - START ))" '. as $s | {service_seconds:$secs, services:$s}' "$RESULT" >"$RESULT.t" && mv "$RESULT.t" "$RESULT"
jq -r '.services[] | "  \(.name): \(.state) :\(.port)"' "$RESULT" >&2
log "service convergence finished in $(( $(now) - START ))s"
